export const GET_CONCOURS_PENDING= "GET_CONCOURS_PENDING";
export const GET_CONCOURS_SUCCESS= "GET_CONCOURS_SUCCESS";
export const GET_CONCOURS_FAILURE= "GET_CONCOURS_FAILURE";

export const QUEL_CONCOURS = "QUEL_CONCOURS";

export const GET_QUESTIONS_PENDING = "GET_QUESTIONS_PENDING";
export const GET_QUESTIONS_SUCCESS = "GET_QUESTIONS_SUCCESS";
export const GET_QUESTIONS_FAILURE = "GET_QUESTIONS_FAILURE";

export const GET_REGLAGES_PENDING = "GET_REGLAGES_PENDING";
export const GET_REGLAGES_SUCCESS = "GET_REGLAGES_SUCCESS";
export const GET_REGLAGES_FAILURE = "GET_REGLAGES_FAILURE";



